MPPI:
  motion_model: "omni"
  model_dt: 0.1
  time_steps: 20
  batch_size: 256
  iteration_count: 1
  temperature: 0.2
  gamma: 0.015

  vx_max: 0.6
  vx_min: -0.3
  vy_max: 0.4
  vy_min: -0.4
  wz_max: 0.8
  wz_min: -0.8
  ax_max: 1.0
  ax_min: -1.0
  ay_max: 1.0
  ay_min: -1.0
  az_max: 1.2
  az_min: -1.2
  vx_std: 0.35
  vy_std: 0.25
  wz_std: 0.45
  retry_attempt_limit: 1
  open_loop: false
  seed: 0
  debug: true

  max_obs_num: 300

  TrajectoryValidator:
    collision_lookahead_time: 1.2
    collision_margin_distance: 0.20

  Critics:
    ConstraintCritic:
      enabled: true
      cost_power: 1
      cost_weight: 4.0
    GoalCritic:
      enabled: true
      cost_power: 1
      cost_weight: 6.0
      threshold_to_consider: 2.5
    GoalAngleCritic:
      enabled: true
      cost_power: 1
      cost_weight: 2.0
      threshold_to_consider: 1.2
    ObstaclesCritic:
      enabled: true
      cost_power: 1
      repulsion_weight: 1.5
      critical_weight: 35.0
      collision_cost: 100000.0
      collision_margin_distance: 0.20
      near_goal_distance: 0.35
      repulsion_distance: 0.9
    PathAlignCritic:
      enabled: true
      cost_power: 1
      cost_weight: 2.0
      max_path_occupancy_ratio: 0.10
      trajectory_point_step: 2
      threshold_to_consider: 0.3
      offset_from_furthest: 6
      use_path_orientation: false
    PathFollowCritic:
      enabled: true
      cost_power: 1
      cost_weight: 4.0
      offset_from_furthest: 4
      threshold_to_consider: 0.3
    PathAngleCritic:
      enabled: true
      cost_power: 1
      cost_weight: 1.5
      offset_from_furthest: 3
      threshold_to_consider: 0.4
      max_angle_to_furthest: 0.785398
      mode: 1
    PreferForwardCritic:
      enabled: false
      cost_power: 1
      cost_weight: 2.0
      threshold_to_consider: 0.5
    VelocityDeadbandCritic:
      enabled: true
      cost_power: 1
      cost_weight: 20.0
      deadband_velocities: [0.0, 0.0, 0.0]
    TwirlingCritic:
      enabled: true
      cost_power: 1
      cost_weight: 3.0
      pose_tolerance: 0.1

  vertices:
    - [[0.45, 0.23], [-0.38, 0.23], [-0.38, -0.23], [0.45, -0.23]]
