uwb_teb_follow_node:
  ros__parameters:
    uwb_topic: /uwb/target_point
    odom_frame: odom
    base_frame: base_footprint
    uwb_frame: base_footprint
    use_latest_tf: false
    transform_timeout_sec: 0.2

    target_topic: /uwb_teb/target
    path_topic: /uwb_teb/path
    target_valid_topic: /follow/target_valid
    status_topic: /follow/uwb_teb_status

    planner_action: /compute_path_to_pose
    planner_id: GridBased

    follow_distance_m: 1.0
    planner_timeout_sec: 1.0
    goal_update_distance_m: 0.10
    goal_update_angle_rad: 0.0872664626
    min_path_poses: 2

    publish_rate_hz: 5.0
